apiVersion: service-operator.aws/v1alpha1
kind: CloudFormationTemplate
metadata:
  name: snstopic
data:
  key: snstopic.yaml
  template: |
    AWSTemplateFormatVersion: 2010-09-09
    Description: 'AWS Service Operator - Amazon SNS Topic (aso-1otq2cgcp)'
    Parameters:
      Namespace:
        Description: >-
          This is the namespace for the Kubernetes object.
        Type: String
      ResourceVersion:
        Type: String
        Description: >-
          This is the resource version for the Kubernetes object.
      ResourceName:
        Description: >-
          This is the resource name for the Kubernetes object
        Type: String
      ClusterName:
        Description: >-
          This is the cluster name for the operator
        Type: String
    Resources:
      SNSTopic:
        Type: 'AWS::SNS::Topic'

    Outputs:
      TopicARN:
        Value: !Ref SNSTopic
        Description: Name of the topic