apiVersion: service-operator.aws/v1alpha1
kind: DynamoDB
metadata:
  name: example-table-name
spec:
  hashAttribute:
    name: user_id
    type: S
  rangeAttribute:
    name: created_at
    type: S
  readCapacityUnits: 5
  writeCapacityUnits: 5
