apiVersion: service-operator.aws/v1alpha1
kind: ElastiCache
metadata:
  name: memcached13
spec:
  cacheSubnetGroupName: "loadtest-cluster-k8s"
  vpcSecurityGroupIds: "sg-0581b94aa3c0db58c, sg-02b6d0034e8c2fa1b"
  autoMinorVersionUpgrade: true
  engine: memcached
  engineVersion: 1.5.10
  numCacheNodes: 1
  port: 11211
  cacheNodeType: "cache.m4.large"
