---
apiVersion: service-operator.aws/v1alpha1
kind: SNSTopic
metadata:
  name: example-sns-topic

---
apiVersion: service-operator.aws/v1alpha1
kind: SQSQueue
metadata:
  name: example-sqs-queue-name
spec:
  contentBasedDeduplication: true
  delaySeconds: 5
  usedeadletterQueue: false
  maximumMessageSize: 262144
  messageRetentionPeriod: 345600
  visibilityTimeout: 30

---
apiVersion: service-operator.aws/v1alpha1
kind: SNSSubscription
metadata:
  name: example-subscription-name
spec:
  topicName: example-sns-topic
  protocol: sqs
  endpoint: example-sqs-queue-name
