apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Values.issuer }}

spec:
  tls:
  - hosts:
    {{- range $host := .Values.hosts }}
    - {{ $host }}
    {{- end }}
    secretName: {{ .Release.Name }}-tls
  rules:
  {{- range $host := .Values.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Release.Name }}
          servicePort: 80
  {{- end }}
