{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "aws-service-operator.fullname" . }}
  labels:
{{ include "aws-service-operator.helmStandardLabels" . | indent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    - pods
    - configmaps
    - services
    - events
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
    - patch
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - service-operator.aws
    resources:
    - "*"
    verbs:
    - "*"
{{- end -}}
