{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "aws-service-operator.helmStandardLabels" . | indent 4 }}
  name: {{ template "aws-service-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
