{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "aws-service-operator.fullname" . }}
  labels:
{{ include "aws-service-operator.helmStandardLabels" . | indent 4 }}
roleRef:
  name: {{ template "aws-service-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: {{ template "aws-service-operator.fullname" . }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
{{- end }}
