# Default values for aws-service-operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: awsserviceoperator/aws-service-operator
  tag: v0.0.1-alpha4
  pullPolicy: IfNotPresent
  #pullSecret: your-k8-secet-to-use (not deployed by chart, but you can reference existing one)

## App config
operator:
  #accountId: 123456789012
  #bucket: aws-operator
  #clusterName: aws-operator
  #config: "$HOME/.aws-operator.yaml"
  #kubeconfig:
  #logfile:
  #loglevel:
  #region: us-west-2
  #resources: s3bucket,dynamodb

## Pod Affinity
affinity: {}

## Extra args to pass to aws-service-operator
extraArgs:
  #- --help

## A list of additional environment variables
extraEnv:
  #- name: my_env
  #  value: my_value

## Additional Volumes and mounts
extraVolumes:
  #- hostPath:
  #    path: /var/log
  #  name: logs
extraVolumeMounts:
  #- name: logs
  #  mountPath: /host/var/log
  #  readOnly: true

## Node Selector
nodeSelector:
  #disktype: ssd

## Pod Annotations
podAnnotations:
  #iam.amazonaws.com/role: arn:aws:iam::<ACCOUNT_ID>:role/aws-service-operator

## Deployment replica count
replicas: 1

## RBAC roles and bindings
rbac:
  create: true
  # Ignored if rbac.create is true
  serviceAccountName: default

## Pod Resources
resources:
  #requests:
  #  memory: "64Mi"
  #  cpu: "250m"
  #limits:
  #  memory: "128Mi"
  #  cpu: "500m"

## Pod Tolerations
tolerations:
  #- key: "node.kubernetes.io/not-ready"
  #  operator: "Exists"
  #  effect: "NoExecute"
  #  tolerationSeconds: 6000
