apiVersion: v2
name: basic-http-server
description: A simple helm chart for deploying http apps to coopernetes. To make it publicly routable, set the host value. To add a persistent volume, set the disk value.
type: application
version: 0.1.5
