apiVersion: service-operator.aws/v1alpha1
kind: ModelDefinition
metadata:
  name: CloudFormationTemplateResource
spec:
  kind: CloudFormationTemplate
  type: Data
  queue: false
  useCloudFormation: false
  resource:
    name: cloudformationtemplate
    plural: cloudformationtemplates
    shortNames:
    - name: cft
    - name: cfts
    - name: cfn
    - name: cfns
    - name: cloudformation
    scope: Namespaced
  body:
    schema:
      title: CloudFormationTemplate
      type: object
      properties:
      - key: key
        type: string
        description: |
          Key is the S3 Key you want to store this as.
        structKey: Key
      - key: template
        type: string
        description: |
          Template represents the cloudformation raw temple in either JSON or
          YAML but represented as a string type.
        structKey: Template
  output:
    schema:
      type: object
      properties:
      - key: url
        type: string
        description: |
          This is the finally URL for the asset.
        structKey: URL
        templateKey: URL

  customizations:
    package: github.com/awslabs/aws-service-operator/pkg/customizations/cloudformationtemplate
    add: cloudformationtemplate.OnAdd
    update: cloudformationtemplate.OnUpdate
    delete: cloudformationtemplate.OnDelete
