ingress:
  enabled: true
  certManager: true
  hostname: wordpress.coopernetes.colab.coop
  tls: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
