repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard/
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: jetstack
  url: https://charts.jetstack.io
- name: kubecost
  url: https://kubecost.github.io/cost-analyzer/

releases:
  ### Dashboard
  - name: kubernetes-dashboard
    namespace: kube-system
    chart: kubernetes-dashboard/kubernetes-dashboard
    values:
    - fullnameOverride: 'kubernetes-dashboard'
  ### Ingress and SSL Certificates
  # NOTE: there are two nginx ingress charts, one maintained my nginx and one maintained by the kubernetes community.
  # we use the community one (ingress-nginx) rather than the nginx one (nginx-ingress). When reading tutorials make
  # sure to pay attention to which ingress they are referring to. It's availible at https://github.com/kubernetes/ingress-nginx
  - name: ingress-nginx
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 2.1.0
    set:
      - name: rbac.create
        value: true
    values:
      - controller:
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 0.15.0
    set:
      - name: installCRDs
        value: true
  - name: cluster-issuers
    namespace: cert-manager
    chart: ./charts/cluster-issuers/
  ### Cost analysis
  - name: kubecost
    namespace: kubecost
    chart: kubecost/cost-analyzer
    set:
      - name: kubecostToken
        value: aWFuQGNvbGFiLmNvb3A=xm343yadf98
  ### Log Aggregation
  - name: elasticsearch
    namespace: system-logging
    chart: bitnami/elasticsearch
  - name: kibana
    namespace: system-logging
    chart: bitnami/kibana
    set:
      - name: elasticsearch.enabled
        value: false
      - name: elasticsearch.external.hosts[0]
        value: ELASTICSEARCH-COORDINATING-NODE-NAME
      - name: elasticsearch.external.port
        value: 9200
      - name: service.type
        value: LoadBalancer
  - name: fluentd-config
    namespace: system-logging
    chart: ./charts/fluentd-config/
  - name: fluentd
    namespace: system-logging
    chart: bitnami/kibana
    set:
      - name: aggregator.configMap
        value: elasticsearch-output
      - name: forwarder.configMap
        value: apache-log-parser
      - name: aggregator.extraEnv[0].name
        value: ELASTICSEARCH_HOST
      - name: aggregator.extraEnv[0].value
        value: ELASTICSEARCH-COORDINATING-NODE-NAME
      - name: aggregator.extraEnv[1].name
        value: ELASTICSEARCH_PORT
      - name: aggregator.extraEnv[1].value
        value: 9200
      - name: forwarder.extraEnv[0].name
        value: FLUENTD_DAEMON_USER
      - name: forwarder.extraEnv[0].value
        value: root
      - name: forwarder.extraEnv[1].name
        value: FLUENTD_DAEMON_GROUP
      - name: forwarder.extraEnv[1].value
        value: root
