repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard/
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: jetstack
  url: https://charts.jetstack.io
- name: kubecost
  url: https://kubecost.github.io/cost-analyzer/
- name: akomljen
  url: https://raw.githubusercontent.com/komljen/helm-charts/master/charts/
- name: vmware-tanzu
  url: https://vmware-tanzu.github.io/helm-charts

# We need to disable validation because we install CRDs and their associated custom resources in one pass
# https://github.com/roboll/helmfile/blob/1e260e4a5ecd57a4c84cdbc98f569a52b7735bb2/pkg/state/state.go#L193-L196.
# This requires helmfile v0.125.0
helmDefaults:
  disableValidation: true

releases:
  ### Dashboard
  - name: kubernetes-dashboard
    namespace: kube-system
    chart: kubernetes-dashboard/kubernetes-dashboard
    values:
    - fullnameOverride: 'kubernetes-dashboard'
  ### Ingress and SSL Certificates
  # NOTE: there are two nginx ingress charts, one maintained my nginx and one maintained by the kubernetes community.
  # we use the community one (ingress-nginx) rather than the nginx one (nginx-ingress). When reading tutorials make
  # sure to pay attention to which ingress they are referring to. It's availible at https://github.com/kubernetes/ingress-nginx
  - name: ingress-nginx
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 2.1.0
    set:
      - name: rbac.create
        value: true
    values:
      - controller:
          extraArgs:
            enable-ssl-passthrough: true
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 0.15.0
    set:
      - name: installCRDs
        value: true
  - name: cluster-issuers
    namespace: cert-manager
    chart: ./charts/cluster-issuers/
  ### Cost analysis
  # They apparently just deploy prometheus operator for kuebcost.
  # Remove for now because it causes a conflict. If we want, we can add it back later.
  # We can install the kubecost dashboard instead, I think: https://grafana.com/grafana/dashboards/8670
   #- name: kubecost
   #  namespace: kubecost
   #  version: 1.62.0
   #  chart: kubecost/cost-analyzer
   #  set:
   #    - name: kubecostToken
   #      value: aWFuQGNvbGFiLmNvb3A=xm343yadf98
  ### Log Aggregation
  # Typically only needed for large clusters with lots of logs.
  # For small clusters, you can grab the logs of an individual pod with kuebctl logs.
   #- name: es-operator
   #  namespace: system-logging
   #  chart: akomljen/elasticsearch-operator
   #- name: efk
   #  namespace: system-logging
   #  chart: akomljen/efk
  ### Backups
  - name: velero
    namespace: system-backup
    chart: vmware-tanzu/velero
    version: 2.12.15
    values:
      - ./values/velero.yaml.gotmpl
