apiVersion: service-operator.aws/v1alpha1
kind: ModelDefinition
metadata:
  name: ECRRepositoryResource
spec:
  kind: ECRRepository
  type: Spec # can be Spec or Data
  queue: true
  useCloudFormation: true
  resource:
    name: ecrrepository
    plural: ecrrepositories
    shortNames:
    - name: ecr
    - name: repository
    scope: Namespaced
  body:
    schema:
      type: object
      properties:
      - key: repositoryName
        type: resourceName
        description: |
          A name for the image repository. If you don't specify a name, AWS
          CloudFormation generates a unique physical ID and uses that ID for
          the repository name. For more information, see Name Type.
        structKey: RepositoryName
        templateKey: RepositoryName
      # - key: lifecyclePolicy
      #   type: string
      #   description: |
      #     A lifecycle policy for the repository.
      #   structKey: LifecyclePolicy
      #   templateKey: LifecyclePolicy
      # - key: repositoryPolicy
      #   type: string
      #   description: |
      #     A policy that controls who has access to the repository and which
      #     actions they can perform on it. For more information, see Amazon ECR
      #     Repository Policies in the Amazon Elastic Container Registry User
      #     Guide.
      #   structKey: repositoryPolicy
      #   templateKey: repositoryPolicy

  output:
    schema:
      type: object
      properties:
      - key: repositoryName
        type: string
        description: |
          A name for the image repository. If you don't specify a name, AWS
          CloudFormation generates a unique physical ID and uses that ID for
          the repository name. For more information, see Name Type.
        structKey: RepositoryName
        templateKey: RepositoryName
      - key: repositoryARN
        type: string
        description: |
          ARN for the Amazon ECR Repository
        structKey: RepositoryARN
        templateKey: RepositoryARN
      - key: repositoryURL
        type: string
        description: |
          URL for the Amazon ECR Repository
        structKey: RepositoryURL
        templatized: true
        template: "{{.Config.AccountID}}.dkr.ecr.{{.Config.Region}}.amazonaws.com/{{.Obj.Name}}"
