apiVersion: service-operator.aws/v1alpha1
kind: ModelDefinition
metadata:
  name: SNSSubscriptionResource
spec:
  kind: SNSSubscription
  type: Spec # can be Spec or Data
  queue: true
  useCloudFormation: true
  resource:
    name: snssubscription
    plural: snssubscriptions
    shortNames:
    - name: subscription
    scope: Namespaced
  body:
    schema:
      type: object
      properties:
      - key: topicName
        type: string
        templatized: true
        template: "{{(call .Helpers.GetSNSTopicByName .Config .Obj.Spec.TopicName .Obj.Namespace).Output.TopicARN}}"
        description: |
          This defines the Name of the topic which translates to an ARN
        structKey: TopicName
        templateKey: TopicARN
      # - key: rawMessageDelivery
      #   type: bool
      #   description: |
      #     true if raw message delivery is enabled for the subscription. Raw
      #     messages are free of JSON formatting and can be sent to HTTP/S and
      #     Amazon SQS endpoints. For more information, see
      #     GetSubscriptionAttributes in the Amazon Simple Notification Service
      #     API Reference.
      #   structKey: RawMessageDelivery
      #   templateKey: RawMessageDelivery
      - key: protocol
        type: string
        description: |
          The subscription's protocol. For more information, see the Subscribe
          Protocol parameter in the Amazon Simple Notification Service API
          Reference.
        structKey: Protocol
        templateKey: Protocol
      - key: endpoint
        type: string
        description: |
          The endpoint that receives notifications from the Amazon SNS topic.
          The endpoint value depends on the protocol that you specify. For more
          information, see the Subscribe Endpoint parameter in the Amazon
          Simple Notification Service API Reference.
        structKey: Endpoint
        templateKey: Endpoint
        templatized: true
        template: '{{if (eq .Obj.Spec.Protocol \"sqs\")}}{{(call .Helpers.GetSQSQueueByName .Config .Obj.Spec.Endpoint .Obj.Namespace).Output.QueueARN }}{{else}}{{.Obj.Spec.Endpoint}}{{end}}'
      - key: queueURL
        type: string
        description: |
          SQS Queue URL if using SQS.
        structKey: QueueURL
        templateKey: QueueURL
        templatized: true
        template: "{{(call .Helpers.GetSQSQueueByName .Config .Obj.Spec.Endpoint .Obj.Namespace).Output.QueueURL }}"

  output:
    schema:
      type: object
      properties:
      - key: subscriptionARN
        type: string
        description: |
          The Subscription ARN for the SNS Topic Subscription.
        structKey: SubscriptionARN
        templateKey: SubscriptionARN
